# .github/workflows/main.yml

name: Advanced Hybrid Trend Crawler V5

on:
  schedule:
    - cron: '0 22 * * *' # 매일 UTC 22시 (한국 오전 7시)
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 사용자가 설정한 GIT_TOKEN Secret을 사용하도록 수정
          token: ${{ secrets.GIT_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          npm install
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python for keyword selection
        run: python keyword_manager.py

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Main Crawler
        env:
          # workflow에서 사용할 환경변수 이름을 사용자가 설정한 Secret 이름으로 수정
          AUTH_STATE: ${{ secrets.AUTH_STATE }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_REPO: ${{ secrets.GIT_REPO }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PROXY_LIST: ${{ secrets.PROXY_LIST }}
        run: node main_crawler.js
